version: "3.9"

services:
  
  web:
    container_name: library
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
       - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=library

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    
    ports:
      - "80:80"
    
    depend_on:
      - postgres